notifications:
  email: false

language: ruby
rvm:
  - 2.4.1
script:
  - bundle exec jekyll build
after_success:
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then ./deploy.sh; fi
branches:
  except:
    - master
