name: Flex
markdown: redcarpet
highlighter: pygments
exclude: ["LICENSE.txt", "README.md"]

baseurl: ""

# Paginate
paginate: 5
paginate_path: "/pagination/page:num/"

# Plugins
gems: 
  - jekyll-multiple-languages-plugin
  - jekyll-paginate

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed


# jekyll-multiple-languages-plugin settings:
languages: ["en", "ru"]

exclude_from_localizations: ["javascript", "images", "scripts", "favicon.ico", "sitemap.xml", "robots.txt"]
