name: Flex
markdown: redcarpet
highlighter: pygments
exclude: ["LICENSE.txt", "README.md"]

baseurl: ""

# Paginate
paginate: 1
paginate_path: "/pagination/page:num/"


# Plugins
gems: 
  - jekyll-multiple-languages-plugin
  - jekyll-paginate


# jekyll-multiple-languages-plugin settings:
languages: ["en", "ru"]

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico", "sitemap.xml", "robots.txt"]
